site_name: Mitoverse

pages:
- Home: index.md
- Getting Started: quick-start.md
- User Guide:
    - Installation: installation.md
    - Contamination Detection: method.md 
    - Interpret Results: analyse.md
- FAQ: faq.md
- About: contact.md



repo_name: genepi/mitoverse
repo_url: https://github.com/genepi/mitoverse
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt

markdown_extensions:
  - admonition

