site_name: Mitoverse
theme: mkdocs

pages:
- Home: index.md
- Installation: installation.md
- Contamination Detection: method.md
- Interpret Results: analyse.md
- FAQ: faq.md
- Contact: contact.md



repo_name: genepi/mitoverse
repo_url: https://github.com/genepi/mitoverse
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt

markdown_extensions:
    - toc:
        permalink:
    - admonition:

