site_name: Mitoverse
copyright: "Cinder is licensed under the <a href='https://github.com/chrissimpkins/cinder/blob/master/LICENSE.md'>MIT license</a>"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - mtDNA-Server 2: mtdna-server/mtdna-server.md
  - Haplocheck: haplocheck/haplocheck.md
  - Contact: contact.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
