site_name: Mitoverse
theme: readthedocs

pages:
- Home: index.md
- Getting Started: getting-started.md
- User Guide:
    - Contamination Method: method.md
    - Interpret Results: interpret.md
- FAQ: faq.md
- About: contact.md



repo_name: genepi/mitoverse
repo_url: https://github.com/genepi/mitoverse
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt

markdown_extensions:
  - admonition
